cmake_minimum_required(VERSION 3.28)

set(CMAKE_CXX_STANDARD 20)
project(linux_homeworks)

add_subdirectory(hello_world)
add_subdirectory(hw7_dupspell/demo/dup_spell_new_pts)
add_subdirectory(hw7_dupspell/demo/dup_spell_separate_lines)
add_subdirectory(hw3_iterators)
add_subdirectory(hw15_ussrearrape)
